services:
  - type: web
    name: certifikat
    env: node
    buildCommand: "bash build.sh && npm install"
    startCommand: "node server.js"
    envVars:
      - key: GEMINI_API_KEY
        sync: false
